name: Execução dos testes do projeto no Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório do projeto
        uses: actions/checkout@v4
        with:
          repository: rhDuxus/desafioAnalistaTestes

      - name: Instalar Docker Compose
        run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
  
      - name: Construir e subir os containers
        run: docker-compose up --build -d

      - name: Aguardando a aplicação iniciar
        run: |
          echo "Aguardando aplicação..."
          sleep 40

      - name: Clonando o repositório
        uses: actions/checkout@v4

      - name: Executando testes Cypress
        uses: cypress-io/github-action@v6

      - name: Salvar vídeos e screenshots caso os testes tenham falhado
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
